services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_checklist
    ports:
      - "6868:6868"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
