version: '3'
services:
  nodejs:
    build: .
    ports:
      - 9999:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      - PORT=3000

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Vnptpmc@123
      MYSQL_DATABASE: dbchecklist
      MYSQL_USER: pmc
      DB_HOST: checklist.pmcweb.vn
      DB_DATABASE_NAME: dbchecklist
      DB_USERNAME: pmc
      DB_PASSWORD: Vnptpmc@123
      DB_PORT: 3306
      DB_DIALECT: mysql
      TYPE: service_account
      PROJECT_ID: pmc-project-407502
      PRIVATE_KEY_ID: ce658b0fb2c4dfc5a5a662abc94ac0fb7c70b29f
      PRIVATE_KEY: \nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEB6o8djWcb5JS\nOJaCSZ1uxnWjzno39gz52XA/AJZ8bjRFh1
          2yuGsKWoGBkVcWAyf88GmyUar6DVQ0\nRjIZTIhL+zLrmovewzyog2lBg1CUT2H7Gu1RsgyU7OVdlLQWSihhwGd/GAa9h4y7\n/MIo1ueHKMtILcgbo69BVmcm/ZRZcZ8ShGsCfrN5gzYqQh5X5wgDEYW5j
          YMvXUT8\nFoxwn1sF7a2WPU6glzjbRIaGm6riItTrdO4QLQKk9Ft5QUlkTPyZ2KfsU2QSeEql\n4iw99ZCgVnKn+lQEtTUUZ1+ywq7LBp2z9gBBHH18ZNW0kEDE/QIyaRNd5BJKZx1O\n2J+UhU1ZAgMBAAEC
          ggEAAj6uOeQGqCR08gEY5CQQq/iU10vhhWuJaYEOcoJAtusS\nKSusLIRFIYi4y/GMpEFj/1cHdtXNlfB6IuEc6MJCG1CknCMYb/QfaTScC3aEATbJ\ngfUke5eE4l22ILS3vTubK8dmyANP7HK1b1+tH4eaf
          ic+8LQpgvuEYcSqCL3FqaKI\n1NIxHTiS5c2bpj2WHqPrUdE6dozTXBxMQ4ceje8Z8NFuCLrwf8QS7DnAF07ZogDa\neyFUGH9xobzM/NI7m3Ccq25+hTn59C4tb44xz8gwSKuKr/o7PZMNX1gHOKMej7hK\npv9
          ijKKGXk9jRF488NHlLOchDmhEGrhEGeHrqGgJSQKBgQDg+nhtI6OKC3W2APrc\nlX6K+ke1c9Da+iGw+U4Sk4pM5N6xm1D+nVpdJB5FZFPvqYCWxkrDB/QlSsmrs8H2\npSRcTESsaoKXUpw9LR1FsaOy1W+R
          DrvVB8ZYVqkP5GQqi2deHD/mSAHaM/XP9z5I\n+2oRmmf2fLEENYJ7RT9eiqODXQKBgQDfD1c6RqijPyYTkhaGwYrIgjSnlfgKTDQd\n4Iq1MqWOaZZ0KliJE+1Q9CX50qbriaautzkZhj9NLE+erLEmLGiL0m
          IG295h7gje\nUdau9LK3zrap0jyLrNgGu49jMVgjbeRdro1+bAgL42ECwLrArdRvCtppRmXgNSv8\nNZgL4pauLQKBgF8I7v4LY/XYSW0MlOvBKqdCejAoMD2QE9NSPKyULoO02m1kEp67\nkYRu0Wq2qs4+Z9dJ
          BCPGpFdsdCxXzsOFlwp2HTxH8cpCV0VwXUEnfOL6ThqUgrvG\ngP6n/Np9u+JM6OlUPZnlKQMnl9q1slXZ/kBZXTk+CvigMfIomlAxeEjxAoGBAKMi\nGw85wfeyJWzGuMbRIWjHIS83VPJjDPKU15zxb3cZ7bk
          Dh0CpXDSKeoOc9gro3wiE\nY7QxJHaSY6COd/iNHeC0epC9mIRSjBXcEIBf4ZzgB2NnqHQWct9pqNJIskcnBY8m\nK8E7zR60qqxSu8JS3zxe2aGIpNU2zfZkU9DNZJn5AoGAOLkQ3twzVT+tmSQjeeXH\n2Yege
          c3GO+9YIMuSYSPeX2ia8Cv256YyFrqQWo1NoYtOSyYuKUXNJ2CougenSPz4\nieKtjtLdGwJcGCXvwRS8sMLJonJVZdWL03jbQ4EUwP1yNZXwoFZKxlZRiqFsrZ2J\n8Hx
          rbF7EO2fWW+tGc7/MMdg=\n
      CLIENT_EMAIL: checklistpmc@pmc-project-407502.iam.gserviceaccount.com
      CLIENT_ID: 113906029046327434872
      AUTH_URI: https://accounts.google.com/o/oauth2/auth
      TOKEN_URI: https://oauth2.googleapis.com/token
      AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
      CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/checklistpmc%40pmc-project-407502.iam.gserviceaccount.com
      UNIVERSE_DOMAIN: googleapis.com

      PARENT_NAME: 12zxC84gZSmMxFmrvyxTZfNfVWvnAsNuz
      SCOPES : https://www.googleapis.com/auth/drive
